### PR TITLE
boilerplate: add kubestack

### PR DESCRIPTION
**Pull request by pst**

### CODE REVIEW

**Comment by shuaibiyy** [comment]
Should this be in the "Terraform Enterprise" section? Also, I guess the title should be "Kubestack GitOps Framework" or "Kubestack".

**Comment by chenrui333** [comment]
Agree, this should be in the enterprise section.

**Comment by pst** [comment]
Kubestack is a framework, its CLI scaffolds a Terraform repository for one or more managed K8s offerings (AKS, EKS or GKE). There is nothing exclusively enterprise about it. Because of this, and the scaffolding aspect, boilerplate seems like the appropriate section to me.

**Comment by chenrui333** [comment]
I see, thanks for explaining it. Merging.

**Pull request merged**
